stages:
  - install
  - quality
  - build

install:
  stage: install
  tags:
    - test
  script:
    - npm install
  artifacts:
    name: "artifacts"
    expire_in: 1 week
    untracked: true
    paths:
      - node_modules/

linting:
  stage: quality
  tags:
    - test
  script:
    - npm run lint
  dependencies:
    - install

run_tests:
  stage: quality
  tags:
    - test
  script:
    -  npm run test
  dependencies:
    - install
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

build:
  stage: build
  tags:
    - test
  script:
    - CI=false npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
      - .nuxt
  dependencies:
    - run_tests
    - linting